# Generated by Django 5.0.2 on 2024-02-22 08:46

import django.core.validators
import events.validators
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_category_options_event_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(validators=[events.validators.datetime_in_future]),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='sub_title',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[functools.partial(events.validators.bad_word_filter, *(['evil', 'bad', 'doof'],), **{})]),
        ),
    ]
